#!/bin/bash

set -e
termux=0

if echo $PREFIX | grep 'com.termux' -q; then
    temrux=1
fi

if [ $termux -eq 1 ]; then
    obfuscate-dict/prebuilt/secret-mkdict
else
    cargo run --manifest-path=obfuscate-dict/Cargo.toml -r --bin secret-mkdict
fi

secret_dict=092wubi_secret.dict.yaml
secret_schema=092wubi_secret.schema.yaml
mv out "$secret_dict"
sed -i 's/092wubi/092wubi_secret/g' "$secret_dict"

cp 092wubi.schema.yaml "$secret_schema"
sed -i 's/schema_id: 092wubi/schema_id: 092wubi_secret/g' "$secret_schema"
sed -i 's/dictionary: 092wubi/dictionary: 092wubi_secret/g' "$secret_schema"
sed -i 's/- table_translator@translator_extend//g' "$secret_schema"
sed -i 's/name: "五笔"/name: "092wubi_secret"/g' "$secret_schema"

cp 092wubi.custom.yaml 092wubi_secret.custom.yaml

patch default.custom.yaml << EOF
@@ -10,6 +10,7 @@ patch:
     - schema: luna_pinyin
     - schema: ipa_yunlong
     - schema: latin_international
+    - schema: 092wubi_secret
   "switcher/hotkeys": # 将默认的 F4热键 更改为ctrl+~
     - "Control+grave"
     - "Control+F8"
EOF
