#!/bin/bash

cargo build --manifest-path=tools-rs/Cargo.toml -r
tools-rs/target/release/secret-mkdict

secret_dict=092wubi_secret.dict.yaml
secret_schema=092wubi_secret.schema.yaml
mv out "$secret_dict"
sed -ie 's/092wubi/092wubi_secret/g' "$secret_dict"

cp 092wubi.schema.yaml "$secret_schema"
sed -it 's/schema_id: 092wubi/schema_id: 092wubi_secret/g' "$secret_schema"
sed -it 's/dictionary: 092wubi/dictionary: 092wubi_secret/g' "$secret_schema"
sed -it 's/- table_translator@translator_extend//g' "$secret_schema"
sed -it 's/name: "五笔"/name: "092wubi_secret"/g' "$secret_schema"

cp 092wubi.custom.yaml 092wubi_secret.custom.yaml

patch default.custom.yaml << EOF
@@ -10,6 +10,7 @@ patch:
     - schema: luna_pinyin
     - schema: ipa_yunlong
     - schema: latin_international
+    - schema: 092wubi_secret
   "switcher/hotkeys": # 将默认的 F4热键 更改为ctrl+~
     - "Control+grave"
     - "Control+F8"
EOF
