#!/bin/bash

(
cat 092wubi.dict.yaml | tail +21 | awk '{print $2"\t"$1}'
cat 092K_ci.dict.yaml | tail +21 | awk '{print $2"\t"$1}'
cat 092wubi_supp2.dict.yaml | tail +21 | awk '{print $2"\t"$1}'
cat 092wubi_supp1.dict.yaml | tail +21 | awk '{print $2"\t"$1}'
cat 092wubi_U.dict.yaml | tail +21 | awk '{print $2"\t"$1}'
# cat messy.dict.yaml | tail +21 | awk '{print $1"\t"$2}'
cat named_ipa_diacritics.dict.yaml | tail +8 | awk '{print "/nipa"$2"\t"$1}'
cat ipa_yunlong.dict.yaml | tail +14 | awk '{print "/ipa"$2"\t"$1}'
cat html_chars.dict.yaml | tail +9 | awk '{print "/hc"$2"\t"$1}'
cat emoji.dict.yaml | tail +10 | awk '{print "/em"$2"\t"$1}'
cat latin_international.dict.yaml | tail +23 | awk '{print "/lt"$2"\t"$1}'
) | ruby -e 'puts STDIN.readlines.uniq' > z92.txt

echo Done

