#!/bin/bash

set -e

[ $# == 0 ] && echo 'Usage command <tutu-dir>' && exit 1

tutu_dir="$1"
cp -v "$tutu_dir"/tigress.dict.yaml tiger_zi.dict.yaml
sed '1s/.*/name: tiger_zi/' tiger_zi.dict.yaml | dos2unix | sponge tiger_zi.dict.yaml

cat > .patch << EOF
--- -	2023-02-14 21:39:20.504372864 +0800
+++ tiger_zi.dict.yaml	2023-02-14 21:37:01.556666362 +0800
@@ -14,9 +14,6 @@
       formula: "AaBaCaCb"
     - length_in_range: [4, 10]
       formula: "AaBaCaZa"
-import_tables:
-  - tigress_ci
-  - tigress_simp_ci
 ...

 的	10359470	u	un

EOF
patch tiger_zi.dict.yaml .patch

cp -v "$tutu_dir"/tigress_ci.dict.yaml tiger_ci.dict.yaml
sed '1s/.*/name: tiger_ci/' tiger_ci.dict.yaml | dos2unix | sponge tiger_ci.dict.yaml
cat > .patch << EOF
--- -	2023-02-14 21:54:31.525331645 +0800
+++ tiger_ci.dict.yaml	2023-02-14 21:54:11.826666672 +0800
@@ -15,8 +15,8 @@
       formula: "AaBaCaCb"
     - length_in_range: [4, 99]
       formula: "AaBaCaZa"
-
 ...
+
 我们	116006	tuja
 自己	109686	oivj
 一个	105148	fijg

EOF
patch tiger_ci.dict.yaml .patch

rm .patch
